services:
  military-db:
    image: postgres:15-alpine
    container_name: military-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: military_db
      POSTGRES_USER: military_user      # <--- Запам'ятай це
      POSTGRES_PASSWORD: military_pass  # <--- І це
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U military_user -d military_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - military-network

  # --- ДОДАНО REDIS ---
  redis:
    image: redis:7-alpine
    container_name: military-warehouse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - military-network

volumes:
  postgres_data:
  redis_data: # <--- Volume для Redis

networks:
  military-network:
    driver: bridge